spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_spin-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone = GMT&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.ndky.exam.pojo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full


shiro:
  login-url: /welcome
  unauthorized-url: /unauthorized
  anon-urls:
    - /login
    - /layuimini/**
    - /baiduyz/**
    - /my/**
server:
  servlet:
    context-path: /spindemo

